/** Text helpers shared by the harness adapters. */

export function clip(text: string, max: number): string {
  return text.length > max ? text.slice(0, max - 1) + '…' : text
}

export function firstLine(text: string, max = 120): string {
  const line = text.trim().split(/\r?\n/, 1)[0] ?? ''
  const more = text.trim().includes('\n')
  return clip(line, max) + (more && line.length < max ? ' …' : '')
}

/**
 * Content that harnesses inject into the "user" role but that the human never
 * typed: reminders, environment blocks, IDE context, continuation summaries.
 */
const INJECTED_PREFIXES = [
  '<system-reminder',
  '<local-command-stdout',
  '<local-command-stderr',
  '<local-command-caveat',
  '<ide_',
  '<task-notification',
  '<available-deferred-tools',
  '<system_instruction',
  '<environment_context',
  '<user_instructions',
  '<turn_aborted',
  '<subagent_notification',
  '<permissions instructions',
  '# AGENTS.md instructions for',
  'This session is being continued from a previous conversation',
  'Caveat: The messages below were generated by the user while running local commands',
]

const CODEX_IDE_CONTEXT = '# Context from my IDE setup:'
const CODEX_REQUEST_MARKER = '## My request for Codex:'

/**
 * Return the text a human actually typed, or `null` when the message is pure
 * harness injection. Slash-command envelopes are rendered as `/command args`.
 */
export function humanText(raw: string): string | null {
  const text = raw.trim()
  if (!text) return null
  if (text.startsWith('<command-name>') || text.startsWith('<command-message>')) {
    const name = /<command-name>\s*([^<]*?)\s*<\/command-name>/.exec(text)?.[1]
    const args = /<command-args>([\s\S]*?)<\/command-args>/.exec(text)?.[1]?.trim()
    if (!name) return null
    const cmd = name.startsWith('/') ? name : `/${name}`
    return args ? `${cmd} ${args}` : cmd
  }
  if (text.startsWith(CODEX_IDE_CONTEXT)) {
    const i = text.indexOf(CODEX_REQUEST_MARKER)
    if (i < 0) return null
    return text.slice(i + CODEX_REQUEST_MARKER.length).trim() || null
  }
  if (INJECTED_PREFIXES.some((p) => text.startsWith(p))) return null
  return text
}

/** Display a path relative to `cwd` when it lives inside it. Case-insensitive on Windows-style paths. */
export function relPath(p: string, cwd?: string): string {
  const norm = p.replace(/\\/g, '/')
  if (!cwd) return norm
  const base = cwd.replace(/\\/g, '/').replace(/\/+$/, '')
  const windowsish = /^[a-zA-Z]:\//.test(base)
  const a = windowsish ? norm.toLowerCase() : norm
  const b = windowsish ? base.toLowerCase() : base
  if (a === b) return '.'
  if (a.startsWith(b + '/')) return norm.slice(base.length + 1)
  return norm
}

export function basename(p: string): string {
  const parts = p.replace(/\\/g, '/').replace(/\/+$/, '').split('/')
  return parts[parts.length - 1] || p
}

/**
 * Shrink an arbitrary tool input for display: long strings are clipped, deep
 * structures flattened. Keeps the wire small without losing the gist.
 */
export function compactInput(value: unknown, maxString = 600, depth = 0): unknown {
  if (value === null || value === undefined) return value
  if (typeof value === 'string') return clip(value, maxString)
  if (typeof value !== 'object') return value
  if (depth > 3) return Array.isArray(value) ? `[${value.length} items]` : '{…}'
  if (Array.isArray(value)) {
    const items = value.slice(0, 20).map((v) => compactInput(v, maxString, depth + 1))
    if (value.length > 20) items.push(`… ${value.length - 20} more`)
    return items
  }
  const out: Record<string, unknown> = {}
  let n = 0
  for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
    if (n++ >= 30) { out['…'] = 'more keys'; break }
    out[k] = compactInput(v, maxString, depth + 1)
  }
  return out
}

/** Join the text parts of a content array (`[{type:'text', text}]`) or return a plain string. */
export function contentText(content: unknown): string {
  if (typeof content === 'string') return content
  if (Array.isArray(content)) {
    return content
      .map((c) => {
        if (typeof c === 'string') return c
        if (c && typeof c === 'object') {
          const o = c as Record<string, unknown>
          if (typeof o.text === 'string') return o.text
          if (o.type === 'image' || o.type === 'input_image') return '[image]'
        }
        return ''
      })
      .filter(Boolean)
      .join('\n')
  }
  return ''
}

export function toMs(timestamp: unknown, fallback = Date.now()): number {
  if (typeof timestamp === 'number') return timestamp < 1e12 ? timestamp * 1000 : timestamp
  if (typeof timestamp === 'string') {
    const t = Date.parse(timestamp)
    if (!Number.isNaN(t)) return t
  }
  return fallback
}

export function isRecord(v: unknown): v is Record<string, unknown> {
  return v !== null && typeof v === 'object' && !Array.isArray(v)
}

export function str(v: unknown): string | undefined {
  return typeof v === 'string' && v.length > 0 ? v : undefined
}

export function num(v: unknown): number {
  return typeof v === 'number' && Number.isFinite(v) ? v : 0
}
